version: '3'
services:
  nextjs-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: nextjs-server
    volumes:
      - ./devsecapp_assistant_app:/app 
    ports:
      - "3000:3000"
    restart: always

  nginx-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx-server
    ports:
      - "80:80"
    restart: always
    depends_on:
      - nextjs-server
